name: 'Sealed Secretes Updater Action'
description: 'GitHub Action for updating your Sealed Secrets manifests based on different secrets inputs'
author: 'Juan Ariza <jariza@vmware.com>'
branding:
  icon: 'lock'
  color: 'yellow'
inputs:
  config_path:
    description: 'Relative path to the configuration file'
    required: true
  only_secrets:
    description: 'Only update provided list of secrets'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config_path }}
    - ${{ inputs.only_secrets }}
